apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: qlsw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qlsw
    app.kubernetes.io/part-of: byoc-app-zvjg
  name: qlswt1w8
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: qlsw
    weight: null
status: {}
