apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: qlsw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qlsw
    app.kubernetes.io/part-of: byoc-app-zvjg
  name: qlsw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: qlsw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: qlsw
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-peua-tenant/byoc-app-zvjg/qlsw@sha256:829bf9b73ff3959f28f3dbe9572a01d7f39675ced48c1e150d326da6bf7d6714
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
